export const categoryList = [
    {
      id: 1,
      value: 'Comedy',
      label: '🎭 Comedy Shows',
    },
    {
      id: 2,
      value: 'Music',
      label: '🎵 Music Shows',
    },
  ];

  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1 ⭐',
    },
    {
      id: 2,
      value: '2',
      label: '2 ⭐',
    },
    {
      id: 3,
      value: '3',
      label: '3 ⭐',
    },
    {
      id: 4,
      value: '4',
      label: '4 ⭐',
    },
    {
      id: 5,
      value: '5',
      label: '5 ⭐',
    },
  ];


export const eventsList = [
    {
        "id": 1,
        "title": "Gaurav Kapoor Live",
        "date": "17th July 2022",
        "time": "7 PM Onwards",
        "category": "Comedy",
        "artist": "Gaurav Kapoor",
        "city": "Noida",
        "location": "Nilgiri Hills Public School, F-1, F Block, Sector 50, Noida, NCR 201303, India",
        "place": "Maharana Pratap Auditorium: Noida",
        "price": "499",
        "duration": "2 hrs",
        "rating": "4",
        "language": "Hindi",
        "description": "Gaurav Kapoor has won almost every open-mic he has ever participated. His razor-sharp wit will cut deep in your weekly blues. You’ll have a good cry..laughing!",
        "cardImg": "https://i.ibb.co/zssx0jK/gaurav-card.png",
        "bannerImg": "https://i.ibb.co/0q4xyJz/gaurav-banner.png"
    },
    {
        "id": 2,
        "title": "Justin Bieber Justice World Tour",
        "date": "18th October 2022",
        "time": "4 PM Onwards",
        "category": "Music",
        "artist": "Justin Bieber",
        "city": "Delhi NCR",
        "location": "Near Lodi Colony, Pragati Vihar, Bhishma Pitamah Marg, Delhi, NCR 110003, India",
        "place": "Jawaharlal Nehru Stadium: Delhi",
        "price": "4000",
        "duration": "6 hrs",
        "rating": "5",
        "language": "English",
        "description": "We’ve caught the #BieberFever and how! Buckle up, Beliebers, for this is one concert you CANNOT afford to miss. With global hits like ‘Lonely’, ‘Peaches’, and more breaking all sorts of international records, this pop-sensation is coming to India!",
        "cardImg": "https://i.ibb.co/5sWs6n0/Bieber.png",
        "bannerImg": "https://i.ibb.co/YNTZgLz/Bieber2.png"
    },
    {//i
        "id": 3,
        "title": "Good Boy Better Show ft.Aashish Solanki",
        "date": "17th JUly 2022",
        "time": "7 PM Onwards",
        "category": "Comedy",
        "artist": "Aashish Solanki",
        "city": "Ahmedabad",
        "location": "H.K. College, Vishalpur, Ellisbridge, Ahmedabad, Gujarat 380006, India",
        "place": "H.K. Hall: Ahemdabad",
        "price": "499",
        "duration": "1 hr 15 mins",
        "rating": "4",
        "language": "Hindi, English",
        "description": "Good boy Aashish is the ideal kid every parent wishes for. His stories and observations will make you laugh and go Ye to mere saath bhi hua hai bhai at the same time. Full of hilarious observations and absolutely CLEAN jokes, the show is for anyone and everyone, especially family. Just make sure that your parents don`t take the good boy home instead of you :P",
        "cardImg": "https://i.ibb.co/G7g5yvq/ashish2.png",
        "bannerImg": "https://i.ibb.co/yg9H233/ashish.png"
    },
    {
        "id": 4,
        "title": "Jo Bolta Hai Vahi Hota Hai ft.Harsh Gujral",
        "date": "28th July 2022",
        "time": "7 PM Onwards",
        "category": "Comedy",
        "artist": "Harsh Solanki",
        "city": "Noida",
        "location": "Nilgiri Hills Public School, F-1, F Block, Sector 50, Noida, NCR 201303, India",
        "place": "Maharana Pratap Auditorium: Noida",
        "price": "799",
        "duration": "1 hr 40 mins",
        "rating": "4",
        "language": "Hindi, English",
        "description": "It takes exemplary courage to sit in the first two rows of a Harsh Gujral`s show because he will get you with his highly witty yet charming style. He has been known to find humour in some of the most regular life situations. He has average north Indian looks and height but he believes that the phrase tall dark and handsome was coined only for him. His style of comedy is spontaneous mixed with great crowd work. Harsh will leave you in splits with his typical rough demeanour and leave you craving for more.",
        "cardImg": "https://i.ibb.co/chqvw3M/harsh2.png",
        "bannerImg": "https://i.ibb.co/sg6nWrs/harsh1.png"
    },
    {
        "id": 5,
        "title": "Bas Kar Bassi ft.Anubhav Singh Bassi",
        "date": "20th August 2022",
        "time": "7 PM Onwards",
        "category": "Comedy",
        "artist": "Anubhav Singh Bassi",
        "city": "Bhopal",
        "location": "Rajbhavan Road, Professors Colony, Near Sardar Vallabh Bhai Patel Polytechnic Chouraha, Bhopal, Madhya Pradesh 462002, India",
        "place": "Ravindra Bhawan: Bhopal",
        "price": "799",
        "duration": "1 hr 40 mins",
        "rating": "3",
        "language": "Hindi, English",
        "description": "This is a show where Anubhav Singh Bassi will tell an honest story about his career choices and his lifestyle. His struggle is worth listening because nothing seems like a struggle. He thinks life has given him everything that he never asked for. `Bas Kar Bassi` is what he said to himself when he was fired by his last boss, it simply means he can`t do a regular job. So come and witness a story full of fun, laughter and alcoholic moments",
        "cardImg": "https://i.ibb.co/ng3CLKs/bassi2.png",
        "bannerImg": "https://i.ibb.co/yV04TMD/bassi1.png"
    },
    {
        "id": 6,
        "title": "Hardwell - Rebels Never Die",
        "date": "11th December 2022",
        "time": "5 PM Onwards",
        "category": "Music",
        "artist": "Hardwell",
        "city": "Delhi NCR",
        "location": "Leisure Valley Park, Near IFCO Chawk Metro Station, Gurugram (Gurgaon), NCR 122009, India ",
        "place": "Leisure Valley Park, Gurgaon",
        "price": "1000",
        "duration": "5 hrs",
        "rating": "5",
        "language": "English",
        "description": "HARDWELL IS BACK - the world’s no. 1 DJ is coming back after announcing his retirement in 2018 with a massive world tour - REBELS NEVER DIE.",
        "cardImg": "https://i.ibb.co/ThScxSL/hardwell2.png",
        "bannerImg": "https://i.ibb.co/NLV43d0/hardwell.png"
    },
    {
        "id": 7,
        "title": "Pannu Yaar! ft.Gurleen Pannu",
        "date": "29th Oct 2022",
        "time": "7 PM Onwards",
        "category": "Music",
        "artist": "Gurleen Pannu",
        "city": "Ahmedabad",
        "location": "H.K. College, Vishalpur, Ellisbridge, Ahmedabad, Gujarat 380006, India",
        "place": "H.K. Hall: Ahmedabad",
        "price": "499",
        "duration": "1 hr 30 min",
        "rating": "4",
        "language": "Hindi, English",
        "description": "‘Pannu Yaar’ is a stand-up comedy show, which will be your one-way ticket into the Pannu-Verse. Her friendly attitude, observational humour, and personal anecdotes will get you in a fit of breathless laughter. Life is full of stories, and Pannu picks the best, presenting them in a manner which reeks of humor and hilarity. Being the centre of attention was always her favourite hobby, and her stories bloom from analysing and observing her surroundings. One may never know, kya pata agla anecdote aapke baare main ho?",
        "cardImg": "https://i.ibb.co/zRg2Jqg/gurleen2.png",
        "bannerImg": "https://i.ibb.co/V2XG9B4/gurleen.png"
    },
    {
        "id": 8,
        "title": "Gaurav Gupta Live",
        "date": "22nd August 2022",
        "time": "7 PM Onwards",
        "category": "Comedy",
        "artist": "Gaurav Gupta",
        "city": "Delhi NCR",
        "location": "DDA Shopping Complex 201, Sri Aurobindo Marg, Aurobindo Palace Market, Hauz Khas, Delhi, NCR 110016, India",
        "place": "Auro Kitchen and Bar: New Delhi",
        "price": "600",
        "duration": "1 hr 30 mins",
        "rating": "3",
        "language": "Hindi, English",
        "description": "Gaurav Gupta is a baniya who is extravagant when it comes to delivering jokes, he is a dentist by profession and a comic by recession, his comedy involves keen observations of daily life, people and funny encounters with them, he has won several open mic competitions like 94.3 FM Radio One LOL contest, Piano Man Tongue in Cheek in Delhi and Chalta Hai Comedy in Mumbai and has performed at Canvas Laugh Club, Mumbai and Delhi. He has also performed at theatre shows in Delhi like Akshara, Alliance Francaise, Lok Kala Manch and so on. He has been performing for prestigious Best in Stand-up Comedy Show at Canvas Laugh Club, Gurgaon cyber hub.",
        "cardImg": "https://i.ibb.co/Ph6d7gF/gg2.png",
        "bannerImg": "https://i.ibb.co/5kjV77q/gg1.png"
    },
    {
        "id": 9,
        "title": "Kunal Kamra Live- Stand up Comedy Show",
        "date": "18th September 2022",
        "time": "7 PM Onwards",
        "category": "Comedy",
        "artist": "Kunal Kamra",
        "city": "Delhi NCR",
        "location": "1st Floor, Trilium Avenue, Sector 29, Near Hudacity Metro Station, Gurugram (Gurgaon), NCR 122009, India",
        "place": "Studio XO Bar: Gurgaon",
        "price": "999",
        "duration": "1 hr 30 mins",
        "rating": "5",
        "language": "Hindi, English",
        "description": "Stand up Comedy Show ft.Kunal Kamra",
        "cardImg": "https://i.ibb.co/bvyDtPc/kunal.png",
        "bannerImg": "https://i.ibb.co/QNcY8Db/kunal2.png"
    },
    {
        "id": 10,
        "title": "HCL Concerts presents Maati Baani",
        "date": "5th August 2022",
        "time": "5 PM Onwards",
        "category": "Music",
        "artist": "Maati Baani",
        "city": "Delhi",
        "location": "1, Copernicus Marg, Mandi House, Opp. Doordarshan Bhavan, Near Connaught Place, Copernicus Marg, Delhi, NCR 110001, India",
        "place": "Little Theatre Group (LTG) Auditorium: Delhi",
        "price": "1000",
        "duration": "2 hrs",
        "rating": "4",
        "language": "English",
        "description": "The conservation and promotion of India`s art and cultural heritage are very close to HCL`s heart. To this end, HCL has been organizing HCL Concerts for many years, dedicated to identifying, evolving and promoting talent rooted in the glorious heritage of Indian classical performing arts.",
        "cardImg": "https://i.ibb.co/VVm81Fr/HCL2.png",
        "bannerImg": "https://i.ibb.co/1bsbxc4/HCL1.png"
    },
    {
        "id": 11,
        "title": "Partition - Stories of Separation",
        "date": "7th August 2022",
        "time": "5 PM Onwards",
        "category": "Music",
        "artist": "Sonam Kalra",
        "city": "Delhi",
        "location": "Lodhi Road, Near Sai Mandir, Delhi, NCR 110003, India",
        "place": "The Stein Auditorium, India Habitat Centre: Delhi",
        "price": "200",
        "duration": "4 hrs",
        "rating": "4",
        "language": "Hindi, English",
        "description": "To mark 75 years of the Partition, award-winning singer and composer Sonam Kalra presents a beautiful and poignant, critically acclaimed experiential music performance that delves into the cataclysmic events and emotions of the Partition of 1947. Using music and theatre to bring to life the poetry and texts of poets and writers of that time along with oral histories and testimonials of survivors of the Partition. Many of the stories we have heard from our grandparents will be lost with the passing of the older generation and this performance is an attempt to preserve and honour them and to serve as lessons for generations to come. In revisiting these stories through music and theatre, Sonam Kalra hopes that the audience will be able to empathize, ponder and realize the way forward. Hopefully, a way of peace and co-existence based on a shared grief, a shared loss, a shared history and a shared love.",
        "cardImg": "https://i.ibb.co/XbgX3j6/partition2.png",
        "bannerImg": "https://i.ibb.co/S0fGBVb/partition.png"
    }
]